language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - drat

before_install:
  - tlmgr install fancyvrb units

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/legacy_deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash legacy_deploy.sh
